"""Calendario Academico Graduacao EaD 2026 - lista canonica.

Fonte: PDF oficial enviado pelo usuario em 2026-05-25.
Restricao: SOMENTE Graduacao (sem Pos-Graduacao).

Estrutura de cada evento:
- categoria: tag para filtrar (aula_inicio, prova_a1, liberacao_notas,
  matricula, transferencia_externa, transferencia_interna, retorno_curso,
  dispensa, ac, estagio, disciplinas_especiais, periodo_letivo,
  planejamento_academico, prova_af, recurso_a1, recurso_af,
  liberacao_notas_af, recesso_docente, feriado, evento, enade).
- titulo: descricao curta para o LLM.
- data_inicio (YYYY-MM-DD): inicio do evento (1o dia).
- data_fim (YYYY-MM-DD ou None): ultimo dia (None = evento de 1 dia).
- mes_ref: mes academico referenciado, ex 'fevereiro', 'agosto' (None
  para eventos genericos do semestre).
- semestre: '2026.1', '2026.2', '2026.1-2', '2027.1' (ou None).
- publico: 'todos', 'calouro', 'veterano', 'concluinte', 'reprovado'.
- observacao: detalhes adicionais opcionais.
"""

CALENDAR_2026_EVENTS = [
    # === PERIODO LETIVO 2026.1 ===
    {"categoria": "periodo_letivo", "titulo": "Início do período letivo 2026.1 e retorno dos docentes",
     "data_inicio": "2026-01-26", "data_fim": None, "mes_ref": None,
     "semestre": "2026.1", "publico": "todos", "observacao": ""},
    {"categoria": "periodo_letivo", "titulo": "Término do semestre letivo 2026.1",
     "data_inicio": "2026-06-30", "data_fim": None, "mes_ref": None,
     "semestre": "2026.1", "publico": "todos", "observacao": ""},
    {"categoria": "planejamento_academico", "titulo": "Planejamento Acadêmico da Graduação EAD 2026-1",
     "data_inicio": "2026-01-26", "data_fim": "2026-01-30", "mes_ref": None,
     "semestre": "2026.1", "publico": "todos", "observacao": "Atividade docente"},
    {"categoria": "recesso_docente", "titulo": "Final do período de Recesso/Férias Docente",
     "data_inicio": "2026-01-23", "data_fim": None, "mes_ref": None,
     "semestre": "2026.1", "publico": "todos", "observacao": ""},

    # === MATRICULA 2026.1 - FEVEREIRO ===
    {"categoria": "matricula", "titulo": "Período de (re)matrícula calouros e veteranos ingresso em Fevereiro",
     "data_inicio": "2025-11-18", "data_fim": "2026-02-15", "mes_ref": "fevereiro",
     "semestre": "2026.1", "publico": "calouro,veterano",
     "observacao": "Ingresso em Fevereiro/2026"},
    {"categoria": "matricula", "titulo": "Início do período de (re)matrícula ingresso em Março",
     "data_inicio": "2026-02-16", "data_fim": None, "mes_ref": "março",
     "semestre": "2026.1", "publico": "calouro,veterano", "observacao": ""},
    {"categoria": "matricula", "titulo": "Período final de (re)matrícula ingresso em Março",
     "data_inicio": "2026-03-08", "data_fim": None, "mes_ref": "março",
     "semestre": "2026.1", "publico": "calouro,veterano", "observacao": ""},
    {"categoria": "matricula", "titulo": "Início do período de (re)matrícula ingresso em Abril",
     "data_inicio": "2026-03-09", "data_fim": None, "mes_ref": "abril",
     "semestre": "2026.1", "publico": "calouro,veterano", "observacao": ""},
    {"categoria": "matricula", "titulo": "Período final de (re)matrícula ingresso em Abril",
     "data_inicio": "2026-04-12", "data_fim": None, "mes_ref": "abril",
     "semestre": "2026.1", "publico": "calouro,veterano", "observacao": ""},
    {"categoria": "matricula", "titulo": "Início do período de (re)matrícula ingresso em Maio",
     "data_inicio": "2026-04-13", "data_fim": None, "mes_ref": "maio",
     "semestre": "2026.1", "publico": "calouro,veterano", "observacao": ""},
    {"categoria": "matricula", "titulo": "Término do prazo para (re)matrícula em 2026.1",
     "data_inicio": "2026-05-12", "data_fim": None, "mes_ref": None,
     "semestre": "2026.1", "publico": "calouro,veterano",
     "observacao": "Última data de matrícula no 1º semestre"},

    # === MATRICULA 2026.2 - AGOSTO ===
    {"categoria": "matricula", "titulo": "Período de matrícula calouros ingresso em Agosto 2026.2",
     "data_inicio": "2026-05-13", "data_fim": "2026-08-16", "mes_ref": "agosto",
     "semestre": "2026.2", "publico": "calouro",
     "observacao": "Ingresso em Agosto/2026 - 2º semestre"},
    {"categoria": "matricula", "titulo": "Período de rematrícula VETERANOS ingresso em Agosto",
     "data_inicio": "2026-06-14", "data_fim": "2026-08-16", "mes_ref": "agosto",
     "semestre": "2026.2", "publico": "veterano", "observacao": ""},
    {"categoria": "matricula", "titulo": "Período final de (re)matrícula ingresso em Agosto",
     "data_inicio": "2026-08-16", "data_fim": None, "mes_ref": "agosto",
     "semestre": "2026.2", "publico": "calouro,veterano", "observacao": ""},
    {"categoria": "matricula", "titulo": "Início do período de (re)matrícula ingresso em Setembro",
     "data_inicio": "2026-08-17", "data_fim": None, "mes_ref": "setembro",
     "semestre": "2026.2", "publico": "calouro,veterano", "observacao": ""},
    {"categoria": "matricula", "titulo": "Período final de (re)matrícula ingresso em Setembro",
     "data_inicio": "2026-09-13", "data_fim": None, "mes_ref": "setembro",
     "semestre": "2026.2", "publico": "calouro,veterano", "observacao": ""},
    {"categoria": "matricula", "titulo": "Início do período de (re)matrícula ingresso em Outubro",
     "data_inicio": "2026-09-14", "data_fim": None, "mes_ref": "outubro",
     "semestre": "2026.2", "publico": "calouro,veterano", "observacao": ""},
    {"categoria": "matricula", "titulo": "Período final de (re)matrícula ingresso em Outubro",
     "data_inicio": "2026-10-11", "data_fim": None, "mes_ref": "outubro",
     "semestre": "2026.2", "publico": "calouro,veterano", "observacao": ""},
    {"categoria": "matricula", "titulo": "Início do período de (re)matrícula ingresso em Novembro",
     "data_inicio": "2026-10-12", "data_fim": None, "mes_ref": "novembro",
     "semestre": "2026.2", "publico": "calouro,veterano", "observacao": ""},
    {"categoria": "matricula", "titulo": "Término do prazo para (re)matrícula em 2026.2",
     "data_inicio": "2026-11-17", "data_fim": None, "mes_ref": None,
     "semestre": "2026.2", "publico": "calouro,veterano",
     "observacao": "Última data de matrícula no 2º semestre"},

    # === MATRICULA 2027.1 ===
    {"categoria": "matricula", "titulo": "Período de (re)matrícula calouros e veteranos ingresso em Fevereiro/27",
     "data_inicio": "2026-11-18", "data_fim": "2027-02-14", "mes_ref": "fevereiro",
     "semestre": "2027.1", "publico": "calouro,veterano",
     "observacao": "Próximo semestre 2027.1"},

    # === PERIODO LETIVO 2026.2 ===
    {"categoria": "periodo_letivo", "titulo": "Início do período letivo 2026.2 e retorno dos docentes",
     "data_inicio": "2026-08-03", "data_fim": None, "mes_ref": None,
     "semestre": "2026.2", "publico": "todos", "observacao": ""},
    {"categoria": "periodo_letivo", "titulo": "Término do semestre letivo 2026.2",
     "data_inicio": "2026-12-19", "data_fim": None, "mes_ref": None,
     "semestre": "2026.2", "publico": "todos", "observacao": ""},
    {"categoria": "planejamento_academico", "titulo": "Planejamento Acadêmico da Graduação EAD 2026-2",
     "data_inicio": "2026-08-03", "data_fim": "2026-08-04", "mes_ref": None,
     "semestre": "2026.2", "publico": "todos", "observacao": "Atividade docente"},
    {"categoria": "recesso_docente", "titulo": "Final do período de Recesso/Férias Docente",
     "data_inicio": "2026-07-31", "data_fim": None, "mes_ref": None,
     "semestre": "2026.2", "publico": "todos", "observacao": ""},
    {"categoria": "recesso_docente", "titulo": "Início do período de Recesso/Férias Docente",
     "data_inicio": "2026-12-19", "data_fim": None, "mes_ref": None,
     "semestre": "2026.2", "publico": "todos", "observacao": ""},

    # === AULAS MENSAIS 2026.1 ===
    {"categoria": "aula_inicio", "titulo": "Início das aulas do mês de Fevereiro",
     "data_inicio": "2026-02-02", "data_fim": None, "mes_ref": "fevereiro",
     "semestre": "2026.1", "publico": "todos", "observacao": ""},
    {"categoria": "aula_inicio", "titulo": "Início das aulas do mês de Março",
     "data_inicio": "2026-03-02", "data_fim": None, "mes_ref": "março",
     "semestre": "2026.1", "publico": "todos", "observacao": ""},
    {"categoria": "aula_inicio", "titulo": "Início das aulas do mês de Abril",
     "data_inicio": "2026-04-01", "data_fim": None, "mes_ref": "abril",
     "semestre": "2026.1", "publico": "todos", "observacao": ""},
    {"categoria": "aula_inicio", "titulo": "Início das aulas do mês de Maio",
     "data_inicio": "2026-05-04", "data_fim": None, "mes_ref": "maio",
     "semestre": "2026.1", "publico": "todos", "observacao": ""},

    # === AULAS MENSAIS 2026.2 ===
    {"categoria": "aula_inicio", "titulo": "Início das aulas do mês de Agosto",
     "data_inicio": "2026-08-03", "data_fim": None, "mes_ref": "agosto",
     "semestre": "2026.2", "publico": "todos", "observacao": ""},
    {"categoria": "aula_inicio", "titulo": "Início das aulas do mês de Setembro",
     "data_inicio": "2026-09-01", "data_fim": None, "mes_ref": "setembro",
     "semestre": "2026.2", "publico": "todos", "observacao": ""},
    {"categoria": "aula_inicio", "titulo": "Início das aulas do mês de Outubro",
     "data_inicio": "2026-10-01", "data_fim": None, "mes_ref": "outubro",
     "semestre": "2026.2", "publico": "todos", "observacao": ""},
    {"categoria": "aula_inicio", "titulo": "Início das aulas do mês de Novembro",
     "data_inicio": "2026-11-03", "data_fim": None, "mes_ref": "novembro",
     "semestre": "2026.2", "publico": "todos", "observacao": ""},

    # === PROVAS A1 (mensal) 2026.1 ===
    {"categoria": "prova_a1", "titulo": "Realização da Prova A1 - Ref. Disciplinas de Fevereiro",
     "data_inicio": "2026-03-13", "data_fim": "2026-03-16", "mes_ref": "fevereiro",
     "semestre": "2026.1", "publico": "todos", "observacao": ""},
    {"categoria": "recurso_a1", "titulo": "Solicitação de Recursos Prova A1 - Ref. Fevereiro",
     "data_inicio": "2026-03-17", "data_fim": None, "mes_ref": "fevereiro",
     "semestre": "2026.1", "publico": "todos", "observacao": ""},
    {"categoria": "prova_a1", "titulo": "Realização da Prova A1 - Ref. Disciplinas de Março",
     "data_inicio": "2026-04-10", "data_fim": "2026-04-13", "mes_ref": "março",
     "semestre": "2026.1", "publico": "todos", "observacao": ""},
    {"categoria": "recurso_a1", "titulo": "Solicitação de Recursos Prova A1 - Ref. Março",
     "data_inicio": "2026-04-14", "data_fim": None, "mes_ref": "março",
     "semestre": "2026.1", "publico": "todos", "observacao": ""},
    {"categoria": "prova_a1", "titulo": "Realização da Prova A1 - Ref. Disciplinas de Abril",
     "data_inicio": "2026-05-08", "data_fim": "2026-05-11", "mes_ref": "abril",
     "semestre": "2026.1", "publico": "todos", "observacao": ""},
    {"categoria": "recurso_a1", "titulo": "Solicitação de Recursos Prova A1 - Ref. Abril",
     "data_inicio": "2026-05-12", "data_fim": None, "mes_ref": "abril",
     "semestre": "2026.1", "publico": "todos", "observacao": ""},
    {"categoria": "prova_a1", "titulo": "Realização da Prova A1 - Ref. Disciplinas de Maio e Junho",
     "data_inicio": "2026-05-29", "data_fim": "2026-06-01", "mes_ref": "maio,junho",
     "semestre": "2026.1", "publico": "todos", "observacao": ""},
    {"categoria": "recurso_a1", "titulo": "Solicitação de Recursos Prova A1 - Ref. Maio e Junho",
     "data_inicio": "2026-06-02", "data_fim": None, "mes_ref": "maio,junho",
     "semestre": "2026.1", "publico": "todos", "observacao": ""},

    # === PROVAS A1 (mensal) 2026.2 ===
    {"categoria": "prova_a1", "titulo": "Realização da Prova A1 - Ref. Disciplinas de Agosto",
     "data_inicio": "2026-09-11", "data_fim": "2026-09-14", "mes_ref": "agosto",
     "semestre": "2026.2", "publico": "todos", "observacao": ""},
    {"categoria": "recurso_a1", "titulo": "Solicitação de Recursos Prova A1 - Ref. Agosto",
     "data_inicio": "2026-09-15", "data_fim": None, "mes_ref": "agosto",
     "semestre": "2026.2", "publico": "todos", "observacao": ""},
    {"categoria": "prova_a1", "titulo": "Realização da Prova A1 - Ref. Disciplinas de Setembro",
     "data_inicio": "2026-10-02", "data_fim": "2026-10-05", "mes_ref": "setembro",
     "semestre": "2026.2", "publico": "todos", "observacao": ""},
    {"categoria": "recurso_a1", "titulo": "Solicitação de Recursos Prova A1 - Ref. Setembro",
     "data_inicio": "2026-10-06", "data_fim": None, "mes_ref": "setembro",
     "semestre": "2026.2", "publico": "todos", "observacao": ""},
    {"categoria": "prova_a1", "titulo": "Realização da Prova A1 - Ref. Disciplinas de Outubro",
     "data_inicio": "2026-11-06", "data_fim": "2026-11-09", "mes_ref": "outubro",
     "semestre": "2026.2", "publico": "todos", "observacao": ""},
    {"categoria": "recurso_a1", "titulo": "Solicitação de Recursos Prova A1 - Ref. Outubro",
     "data_inicio": "2026-11-10", "data_fim": None, "mes_ref": "outubro",
     "semestre": "2026.2", "publico": "todos", "observacao": ""},
    {"categoria": "prova_a1", "titulo": "Realização da Prova A1 - Ref. Disciplinas de Novembro e Dezembro",
     "data_inicio": "2026-11-27", "data_fim": "2026-11-30", "mes_ref": "novembro,dezembro",
     "semestre": "2026.2", "publico": "todos", "observacao": ""},
    {"categoria": "recurso_a1", "titulo": "Solicitação de Recursos Prova A1 - Ref. Novembro e Dezembro",
     "data_inicio": "2026-12-01", "data_fim": None, "mes_ref": "novembro,dezembro",
     "semestre": "2026.2", "publico": "todos", "observacao": ""},

    # === LIBERACAO DE NOTAS A1 ===
    {"categoria": "liberacao_notas", "titulo": "Liberação de Notas da Disciplina de Fevereiro",
     "data_inicio": "2026-03-30", "data_fim": None, "mes_ref": "fevereiro",
     "semestre": "2026.1", "publico": "todos", "observacao": ""},
    {"categoria": "liberacao_notas", "titulo": "Liberação de Notas da Disciplina de Março",
     "data_inicio": "2026-04-27", "data_fim": None, "mes_ref": "março",
     "semestre": "2026.1", "publico": "todos", "observacao": ""},
    {"categoria": "liberacao_notas", "titulo": "Liberação de Notas da Disciplina de Abril",
     "data_inicio": "2026-05-25", "data_fim": None, "mes_ref": "abril",
     "semestre": "2026.1", "publico": "todos", "observacao": ""},
    {"categoria": "liberacao_notas", "titulo": "Liberação de Notas das Disciplinas de Maio e Junho",
     "data_inicio": "2026-06-11", "data_fim": None, "mes_ref": "maio,junho",
     "semestre": "2026.1", "publico": "todos", "observacao": ""},
    {"categoria": "liberacao_notas", "titulo": "Liberação de Notas da Disciplina de Agosto",
     "data_inicio": "2026-09-29", "data_fim": None, "mes_ref": "agosto",
     "semestre": "2026.2", "publico": "todos", "observacao": ""},
    {"categoria": "liberacao_notas", "titulo": "Liberação de Notas da Disciplina de Setembro",
     "data_inicio": "2026-10-19", "data_fim": None, "mes_ref": "setembro",
     "semestre": "2026.2", "publico": "todos", "observacao": ""},
    {"categoria": "liberacao_notas", "titulo": "Liberação de Notas da Disciplina de Outubro",
     "data_inicio": "2026-11-23", "data_fim": None, "mes_ref": "outubro",
     "semestre": "2026.2", "publico": "todos", "observacao": ""},
    {"categoria": "liberacao_notas", "titulo": "Liberação de Notas das Disciplinas de Novembro e Dezembro",
     "data_inicio": "2026-12-07", "data_fim": None, "mes_ref": "novembro,dezembro",
     "semestre": "2026.2", "publico": "todos", "observacao": ""},

    # === PROVA AF (recuperacao) ===
    {"categoria": "prova_af", "titulo": "Realização da Prova AF - Ref. Disciplinas Mensais Reprovadas 2026-1",
     "data_inicio": "2026-06-26", "data_fim": "2026-06-27", "mes_ref": None,
     "semestre": "2026.1", "publico": "reprovado",
     "observacao": "Recuperação para disciplinas mensais reprovadas no 1º semestre"},
    {"categoria": "recurso_af", "titulo": "Solicitação de Recursos Prova AF - 2026-1",
     "data_inicio": "2026-06-28", "data_fim": None, "mes_ref": None,
     "semestre": "2026.1", "publico": "reprovado", "observacao": ""},
    {"categoria": "liberacao_notas_af", "titulo": "Liberação de Notas AF - Ref. Disciplinas Mensais Reprovadas 2026-1",
     "data_inicio": "2026-07-06", "data_fim": None, "mes_ref": None,
     "semestre": "2026.1", "publico": "reprovado", "observacao": ""},
    {"categoria": "prova_af", "titulo": "Realização da Prova AF - Ref. Disciplinas Mensais Reprovadas 2026-2",
     "data_inicio": "2026-12-11", "data_fim": "2026-12-12", "mes_ref": None,
     "semestre": "2026.2", "publico": "reprovado",
     "observacao": "Recuperação para disciplinas mensais reprovadas no 2º semestre"},
    {"categoria": "recurso_af", "titulo": "Solicitação de Recursos Prova AF - 2026-2",
     "data_inicio": "2026-12-13", "data_fim": None, "mes_ref": None,
     "semestre": "2026.2", "publico": "reprovado", "observacao": ""},
    {"categoria": "liberacao_notas_af", "titulo": "Liberação de Notas AF - Ref. Disciplinas Mensais Reprovadas 2026-2",
     "data_inicio": "2026-12-21", "data_fim": None, "mes_ref": None,
     "semestre": "2026.2", "publico": "reprovado", "observacao": ""},

    # === DISCIPLINAS ESPECIAIS ===
    {"categoria": "disciplinas_especiais", "titulo": "Disponibilização de Disciplinas Especiais 2026.1",
     "data_inicio": "2026-02-23", "data_fim": "2026-05-12", "mes_ref": None,
     "semestre": "2026.1", "publico": "concluinte,reprovado",
     "observacao": "Via área de rematrícula"},
    {"categoria": "disciplinas_especiais", "titulo": "Término do prazo para inclusão de Disciplinas Especiais 2026.1",
     "data_inicio": "2026-05-12", "data_fim": None, "mes_ref": None,
     "semestre": "2026.1", "publico": "concluinte,reprovado", "observacao": ""},
    {"categoria": "disciplinas_especiais", "titulo": "Disponibilização de Disciplinas Especiais 2026.2",
     "data_inicio": "2026-08-24", "data_fim": "2026-11-17", "mes_ref": None,
     "semestre": "2026.2", "publico": "concluinte,reprovado",
     "observacao": "Via área de rematrícula"},
    {"categoria": "disciplinas_especiais", "titulo": "Término do prazo para inclusão de Disciplinas Especiais 2026.2",
     "data_inicio": "2026-11-17", "data_fim": None, "mes_ref": None,
     "semestre": "2026.2", "publico": "concluinte,reprovado", "observacao": ""},

    # === SOLICITACOES ===
    {"categoria": "transferencia_externa", "titulo": "Período de Solicitação de 2a. Graduação e Transferência Externa 2026.1",
     "data_inicio": "2025-11-18", "data_fim": "2026-05-12", "mes_ref": None,
     "semestre": "2026.1", "publico": "todos", "observacao": ""},
    {"categoria": "transferencia_externa", "titulo": "Período de Solicitação de 2a. Graduação e Transferência Externa 2026.2",
     "data_inicio": "2026-05-13", "data_fim": "2026-11-13", "mes_ref": None,
     "semestre": "2026.2", "publico": "todos", "observacao": ""},
    {"categoria": "transferencia_interna", "titulo": "Período de Solicitação de Transferência Interna entre Cursos",
     "data_inicio": "2025-11-18", "data_fim": "2026-12-19", "mes_ref": None,
     "semestre": "2026.1-2", "publico": "todos",
     "observacao": "Período abrange o ano todo"},
    {"categoria": "retorno_curso", "titulo": "Período de Solicitação de Retorno ao Curso (Destrancamento) 2026.1",
     "data_inicio": "2025-12-02", "data_fim": "2026-05-06", "mes_ref": None,
     "semestre": "2026.1", "publico": "todos", "observacao": ""},
    {"categoria": "retorno_curso", "titulo": "Período de Solicitação de Retorno ao Curso (Destrancamento) 2026.2",
     "data_inicio": "2026-05-08", "data_fim": "2026-11-06", "mes_ref": None,
     "semestre": "2026.2", "publico": "todos", "observacao": ""},
    {"categoria": "dispensa", "titulo": "Período de Solicitação de Dispensa de Disciplinas 2026.1",
     "data_inicio": "2025-12-22", "data_fim": "2026-06-06", "mes_ref": None,
     "semestre": "2026.1", "publico": "todos", "observacao": ""},
    {"categoria": "dispensa", "titulo": "Período de Solicitação de Dispensa de Disciplinas 2026.2",
     "data_inicio": "2026-06-08", "data_fim": "2026-11-27", "mes_ref": None,
     "semestre": "2026.2", "publico": "todos", "observacao": ""},

    # === ATIVIDADES COMPLEMENTARES ===
    {"categoria": "ac", "titulo": "Período de Envio de Atividades Complementares 2026-1",
     "data_inicio": "2026-01-19", "data_fim": "2026-06-19", "mes_ref": None,
     "semestre": "2026.1", "publico": "todos", "observacao": "ACs do 1º semestre"},
    {"categoria": "ac", "titulo": "Período de Revisão das Atividades Complementares 2026-1",
     "data_inicio": "2026-04-06", "data_fim": "2026-07-17", "mes_ref": None,
     "semestre": "2026.1", "publico": "todos", "observacao": ""},
    {"categoria": "ac", "titulo": "Período de Envio de Atividades Complementares 2026-2",
     "data_inicio": "2026-07-20", "data_fim": "2026-12-14", "mes_ref": None,
     "semestre": "2026.2", "publico": "todos", "observacao": "ACs do 2º semestre"},
    {"categoria": "ac", "titulo": "Período de Revisão das Atividades Complementares 2026-2",
     "data_inicio": "2026-09-07", "data_fim": "2026-12-19", "mes_ref": None,
     "semestre": "2026.2", "publico": "todos", "observacao": ""},

    # === ESTAGIO (TCE) ===
    {"categoria": "estagio", "titulo": "Prazo final para envio de TCE - Cursos da Saúde 2026.1",
     "data_inicio": "2026-03-23", "data_fim": None, "mes_ref": None,
     "semestre": "2026.1", "publico": "todos",
     "observacao": "Termo de Compromisso de Estágio - apenas cursos da Saúde"},
    {"categoria": "estagio", "titulo": "Prazo final para envio de TCE - Demais cursos 2026.1",
     "data_inicio": "2026-05-25", "data_fim": None, "mes_ref": None,
     "semestre": "2026.1", "publico": "todos",
     "observacao": "Termo de Compromisso de Estágio - exceto Saúde"},
    {"categoria": "estagio", "titulo": "Prazo final TCE Obrigatório e Planilhas/Relatórios 2026.1",
     "data_inicio": "2026-06-08", "data_fim": None, "mes_ref": None,
     "semestre": "2026.1", "publico": "todos",
     "observacao": "Via AVA - Estágios Curriculares Obrigatórios"},
    {"categoria": "estagio", "titulo": "Prazo final para envio de TCE - Cursos da Saúde 2026.2",
     "data_inicio": "2026-09-21", "data_fim": None, "mes_ref": None,
     "semestre": "2026.2", "publico": "todos", "observacao": ""},
    {"categoria": "estagio", "titulo": "Prazo final para envio de TCE - Demais cursos 2026.2",
     "data_inicio": "2026-11-09", "data_fim": None, "mes_ref": None,
     "semestre": "2026.2", "publico": "todos", "observacao": ""},
    {"categoria": "estagio", "titulo": "Prazo final TCE Obrigatório e Planilhas/Relatórios 2026.2",
     "data_inicio": "2026-11-23", "data_fim": None, "mes_ref": None,
     "semestre": "2026.2", "publico": "todos", "observacao": ""},

    # === EVENTOS ===
    {"categoria": "evento", "titulo": "Semana de Cursos Graduação EaD (Jornada Acadêmica)",
     "data_inicio": "2026-05-19", "data_fim": "2026-05-20", "mes_ref": None,
     "semestre": "2026.1", "publico": "todos", "observacao": "Jornada Acadêmica"},
    {"categoria": "enade", "titulo": "Exame Nacional de Desempenho dos Estudantes - ENADE",
     "data_inicio": "2026-11-26", "data_fim": None, "mes_ref": None,
     "semestre": "2026.2", "publico": "concluinte",
     "observacao": "Para alunos selecionados na amostra do ENADE"},

    # === FERIADOS NACIONAIS E SP ===
    {"categoria": "feriado", "titulo": "Confraternização Universal",
     "data_inicio": "2026-01-01", "data_fim": None, "mes_ref": "janeiro",
     "semestre": None, "publico": "todos", "observacao": "Feriado nacional"},
    {"categoria": "feriado", "titulo": "Aniversário de São Paulo",
     "data_inicio": "2026-01-25", "data_fim": None, "mes_ref": "janeiro",
     "semestre": None, "publico": "todos", "observacao": "Feriado municipal SP"},
    {"categoria": "feriado", "titulo": "Carnaval",
     "data_inicio": "2026-02-14", "data_fim": "2026-02-18", "mes_ref": "fevereiro",
     "semestre": "2026.1", "publico": "todos", "observacao": "Recesso de Carnaval"},
    {"categoria": "feriado", "titulo": "Paixão de Cristo e Páscoa",
     "data_inicio": "2026-04-03", "data_fim": "2026-04-05", "mes_ref": "abril",
     "semestre": "2026.1", "publico": "todos", "observacao": "Feriado prolongado"},
    {"categoria": "feriado", "titulo": "Tiradentes / Fundação de Brasília",
     "data_inicio": "2026-04-21", "data_fim": None, "mes_ref": "abril",
     "semestre": "2026.1", "publico": "todos", "observacao": "Feriado nacional"},
    {"categoria": "feriado", "titulo": "Dia do Trabalhador",
     "data_inicio": "2026-05-01", "data_fim": None, "mes_ref": "maio",
     "semestre": "2026.1", "publico": "todos", "observacao": "Feriado nacional"},
    {"categoria": "feriado", "titulo": "Corpus Christi",
     "data_inicio": "2026-06-04", "data_fim": None, "mes_ref": "junho",
     "semestre": "2026.1", "publico": "todos", "observacao": "Feriado nacional"},
    {"categoria": "feriado", "titulo": "Independência do Brasil",
     "data_inicio": "2026-09-07", "data_fim": None, "mes_ref": "setembro",
     "semestre": "2026.2", "publico": "todos", "observacao": "Feriado nacional"},
    {"categoria": "feriado", "titulo": "Padroeira do Brasil (Nossa Senhora Aparecida)",
     "data_inicio": "2026-10-12", "data_fim": None, "mes_ref": "outubro",
     "semestre": "2026.2", "publico": "todos", "observacao": "Feriado nacional"},
    {"categoria": "feriado", "titulo": "Finados",
     "data_inicio": "2026-11-02", "data_fim": None, "mes_ref": "novembro",
     "semestre": "2026.2", "publico": "todos", "observacao": "Feriado nacional"},
    {"categoria": "feriado", "titulo": "Proclamação da República",
     "data_inicio": "2026-11-15", "data_fim": None, "mes_ref": "novembro",
     "semestre": "2026.2", "publico": "todos", "observacao": "Feriado nacional"},
    {"categoria": "feriado", "titulo": "Consciência Negra",
     "data_inicio": "2026-11-20", "data_fim": None, "mes_ref": "novembro",
     "semestre": "2026.2", "publico": "todos", "observacao": "Feriado nacional"},
    {"categoria": "feriado", "titulo": "Natal",
     "data_inicio": "2026-12-25", "data_fim": None, "mes_ref": "dezembro",
     "semestre": "2026.2", "publico": "todos", "observacao": "Feriado nacional"},
]


def get_seed_events():
    """Retorna a lista canonica de eventos do calendario 2026."""
    return list(CALENDAR_2026_EVENTS)
